### ISSUE TITLE
Error when running dungeon

### ISSUE THREAD

**Issue by Dizzzlectic** [JulienCHATEAU/SWAutoPlay_GUI#2]
Hello!

Having set-up everything, I'm getting this error when trying to run Garen forest as a test:

```
Exec command : adb -s 192.168.10.105:5555 shell getprop ro.product.model
SM-G950F
SelectedDeviceIndex : 0Exec command : adb -s 192.168.10.105:5555 shell am instrument -w -r -e AverageDungeonTime 21 -e RunCount 1 -e Refill Off -e Difficulty Hell -e StartStage 1 -e StartTestPosition Island -e DungeonName Garen com.example.swautoplay.test/androidx.test.runner.AndroidJUnitRunner
onError: commandError=true message=INSTRUMENTATION_FAILED: com.example.swautoplay.test/androidx.test.runner.AndroidJUnitRunner
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.example.swautoplay.test/androidx.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS_CODE: -1
Error : exit status 1
Stderr : android.util.AndroidException: INSTRUMENTATION_FAILED: com.example.swautoplay.test/androidx.test.runner.AndroidJUnitRunner
	at com.android.commands.am.Instrument.run(Instrument.java:486)
	at com.android.commands.am.Am.runInstrument(Am.java:194)
	at com.android.commands.am.Am.onRun(Am.java:80)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
	at com.android.commands.am.Am.main(Am.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)

onError: commandError=true message=INSTRUMENTATION_FAILED: com.example.swautoplay.test/androidx.test.runner.AndroidJUnitRunner
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.example.swautoplay.test/androidx.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS_CODE: -1
```

**Comment by JulienCHATEAU** [comment]
Hello SpellCraft.

This project is a Graphical User Interface that provides an easier way to use another of my projects called SWAutoPlay. This latter is an Android mobile application supposed to be downloaded on your phone before using the GUI. I advise you to open it with Android Studio and to run it on your phone. As soon as you can open SWAutoPlay mobile application on your phone, the bot is ready and the GUI would be supposed to work.

I know it's harsh to install these two projects as i didn't write any wiki or tutorial yet, I'll try my best to provide any kind of written help as soon as possible. 

Tell me if it helped !
